/**
 * Fetch the live ClinicalTrials.gov OpenAPI spec + metadata and regenerate:
 *   - schema/openapi.pinned.json
 *   - schema/field-dictionary.json
 *
 * Run in an environment with outbound HTTPS access to clinicaltrials.gov.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { request } from "undici";

const BASE = process.env.CTGOV_BASE ?? "https://clinicaltrials.gov/api/v2";

interface FieldNode {
  name?: string;
  piece?: string;
  type?: string;
  description?: string;
  children?: FieldNode[];
}

async function getJson<T>(path: string): Promise<T> {
  const res = await request(BASE + path, {
    method: "GET",
    headers: {
      accept: "application/json",
      "user-agent": "clinicaltrial-mcp-server regen-sdk/0.1",
    },
  });
  if (res.statusCode >= 400) {
    throw new Error(`GET ${path} -> ${res.statusCode}`);
  }
  return (await res.body.json()) as T;
}

function flatten(nodes: FieldNode[], prefix = ""): Array<{ path: string; type: string; doc: string }> {
  const out: Array<{ path: string; type: string; doc: string }> = [];
  for (const n of nodes ?? []) {
    const piece = n.piece ?? n.name ?? "";
    if (!piece) continue;
    const path = prefix ? `${prefix}.${piece}` : piece;
    out.push({
      path,
      type: n.type ?? "unknown",
      doc: (n.description ?? "").trim(),
    });
    if (n.children?.length) out.push(...flatten(n.children, path));
  }
  return out;
}

async function main(): Promise<void> {
  // eslint-disable-next-line no-console
  console.log(`Fetching OpenAPI from ${BASE}/openapi.json ...`);
  const openapi = await getJson<Record<string, unknown>>("/openapi.json");
  const openapiPath = resolve("schema", "openapi.pinned.json");
  writeFileSync(openapiPath, JSON.stringify(openapi, null, 2) + "\n");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${openapiPath}`);

  // eslint-disable-next-line no-console
  console.log(`Fetching /studies/metadata ...`);
  const meta = await getJson<FieldNode[]>("/studies/metadata");
  const fields = flatten(meta).slice(0, 600);
  const dictPath = resolve("schema", "field-dictionary.json");
  writeFileSync(
    dictPath,
    JSON.stringify(
      {
        _comment:
          "Generated by scripts/regenerate-sdk.ts from /studies/metadata. Top 600 fields by document order.",
        fields,
      },
      null,
      2,
    ) + "\n",
  );
  // eslint-disable-next-line no-console
  console.log(`Wrote ${dictPath} with ${fields.length} fields`);
}

main().catch((err: unknown) => {
   
  console.error("regenerate-sdk failed:", err);
  process.exit(1);
});
